# Generated by Django 3.2 on 2021-07-23 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_viaje_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('descripcion', models.CharField(max_length=50, null=True, unique=True, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Descripcion',
                'verbose_name_plural': 'Descripciones',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDescripcion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('descripcion', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Departamento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Descripcion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUbicacion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('ubicacion', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Ubicacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ubicacion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre De La Propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('ubicacion', models.CharField(max_length=50, null=True, unique=True, verbose_name='Ubicacion')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.RenameModel(
            old_name='Destino',
            new_name='Fotos',
        ),
        migrations.RenameModel(
            old_name='HistoricalDestino',
            new_name='HistoricalFotos',
        ),
        migrations.RemoveField(
            model_name='historicalfechadesalida',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalhoradesalida',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnumerodebus',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorigen',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltipodebus',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_de_salida',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='hora_de_salida',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='numero_de_bus',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='tipo_de_bus',
        ),
        migrations.AlterModelOptions(
            name='fotos',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterModelOptions(
            name='historicalfotos',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Foto'},
        ),
        migrations.RenameField(
            model_name='fotos',
            old_name='destino',
            new_name='fotos',
        ),
        migrations.RenameField(
            model_name='historicalfotos',
            old_name='destino',
            new_name='fotos',
        ),
        migrations.DeleteModel(
            name='FechaDeSalida',
        ),
        migrations.DeleteModel(
            name='HistoricalFechaDeSalida',
        ),
        migrations.DeleteModel(
            name='HistoricalHoraDeSalida',
        ),
        migrations.DeleteModel(
            name='HistoricalNumeroDeBus',
        ),
        migrations.DeleteModel(
            name='HistoricalOrigen',
        ),
        migrations.DeleteModel(
            name='HistoricalTipoDeBus',
        ),
        migrations.DeleteModel(
            name='HoraDeSalida',
        ),
        migrations.DeleteModel(
            name='NumeroDeBus',
        ),
        migrations.DeleteModel(
            name='Origen',
        ),
        migrations.DeleteModel(
            name='TipoDeBus',
        ),
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
