# Generated by Django 3.2 on 2021-07-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210722_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='descripcion',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='products.descripcion', verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='ubicacion',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='products.ubicacion', verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='descripcion',
            name='descripcion',
            field=models.CharField(max_length=50, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='fotos',
            field=models.ImageField(null=True, upload_to='propiedades'),
        ),
        migrations.AlterField(
            model_name='historicaldescripcion',
            name='descripcion',
            field=models.CharField(max_length=50, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='historicalfotos',
            name='fotos',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalubicacion',
            name='ubicacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ubicacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Ubicacion'),
        ),
    ]
